public enum InputEnum
{
    NAV_LEFT = 0,
    NAV_RIGHT = 1,
    NAV_UP = 2,
    NAV_DOWN = 3,
    NAV_SELECT = 4,
    NAV_BACK = 5,
    GAME_LEFT = 6,
    GAME_RIGHT = 7,
    GAME_JUMP = 8,
    GAME_SPRINT = 9,
    GAME_ROLL = 10,
    GAME_FIRE_WEAPON = 11,
    GAME_PREV_WEAPON = 12,
    GAME_NEXT_WEAPON = 13,
    GAME_EQUIPMENT_1 = 14,
    GAME_EQUIPMENT_2 = 15,
    GAME_PAUSE = 16,
    DEV_1 = 100,
    DEV_2 = 101,
    DEV_3 = 102,
    DEV_4 = 103,
    DEV_5 = 104
}